name: Deploy CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: prepare build environment
      env:
        GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'xwal'
        git config --global user.email 'chaosky.me@gmail.com'
        npm install -g grunt-cli
        gem install compass
        pip install --user fpdf
        npm install
        npm run bower
    - name: deploy to github
      run: |
        sh ./publish-to-gh-pages.sh
      env:
        CI: true
